pub const SYNCHRONOUS_ROTATION_TOLERANCE: f64 = 1e-4;
pub const MINIMUM_SOLAR_DAY_SECONDS: f64 = 1e-6;
pub const MINIMUM_YEAR_SECONDS: f64 = 1e-6;
pub const ASEASONAL_OBLIQUITY_THRESHOLD_RAD: f64 = 0.001;
pub const ASEASONAL_ECCENTRICITY_THRESHOLD: f64 = 0.001;
pub const DISTANCE_DRIVEN_ECCENTRICITY_THRESHOLD: f64 = 0.01;