pub const DEFAULT_SUTTON_GRAVES_CONSTANT: f64 = 1.74153e-4;
pub const DEFAULT_HULL_EMISSIVITY: f64 = 0.85;
pub const DEFAULT_MAX_STRUCTURAL_TEMPERATURE_K: f64 = 1800.0;
pub const DEFAULT_STRUCTURAL_HULL_EMISSIVITY: f64 = 0.85;

pub const STANTON_NUMBER_BASE: f64 = 0.002;
pub const STANTON_NUMBER_MACH_COEFF: f64 = 0.15;
pub const STANTON_NUMBER_MACH_EXPONENT: f64 = 0.58;

pub const MIN_NOSE_RADIUS_M: f64 = 0.05;
pub const MIN_LATERAL_AREA_M2: f64 = 0.1;

pub const CORRIDOR_SHALLOW_GAMMA_INITIAL_RAD: f64 = -0.001;
pub const CORRIDOR_STEEP_GAMMA_INITIAL_RAD: f64 = -0.4;
pub const CORRIDOR_SEARCH_STEPS: usize = 40;
pub const CORRIDOR_BISECTION_ITERATIONS: usize = 20;

pub const TARGET_APOAPSIS_BISECTION_ITERATIONS: usize = 30;
pub const TARGET_APOAPSIS_TOLERANCE_M: f64 = 1000.0;
pub const TARGET_GAMMA_TOLERANCE_RAD: f64 = 1e-6;
pub const DEFAULT_FALLBACK_ENTRY_ANGLE_RAD: f64 = -0.08;
pub const TARGET_CORRIDOR_APOAPSIS_MULTIPLIER: f64 = 1.5;

pub const ATMOSPHERIC_PASS_DEFAULT_MAX_DURATION_S: f64 = 3600.0;
pub const ATMOSPHERIC_PASS_DEFAULT_DT_S: f64 = 0.5;
pub const ATMOSPHERIC_PASS_FINE_DT_S: f64 = 0.2;
pub const ATMOSPHERIC_PASS_MIN_DT_S: f64 = 0.01;
pub const ATMOSPHERIC_PASS_MAX_DT_S: f64 = 5.0;
pub const ATMOSPHERIC_PASS_MIN_DURATION_S: f64 = 60.0;
pub const ATMOSPHERIC_PASS_HIGH_DENSITY_THRESHOLD: f64 = 1e-7;
pub const ATMOSPHERIC_PASS_EXO_DT_MULTIPLIER: f64 = 2.0;
pub const ATMOSPHERIC_ENTRY_ALTITUDE_BUFFER_M: f64 = 100.0;

pub const CHEBYSHEV_DEFAULT_FIT_DEGREE: usize = 7;