pub const DEFAULT_SUTTON_GRAVES_CONSTANT: f64 = 1.74153e-4;
pub const DEFAULT_HULL_EMISSIVITY: f64 = 0.85;
pub const DEFAULT_STRUCTURAL_HULL_EMISSIVITY: f64 = 0.85;

pub const STANTON_NUMBER_BASE: f64 = 0.002;
pub const STANTON_NUMBER_MACH_COEFF: f64 = 0.15;
pub const STANTON_NUMBER_MACH_EXPONENT: f64 = 0.58;

pub const MIN_NOSE_RADIUS_M: f64 = 0.05;
pub const MIN_LATERAL_AREA_M2: f64 = 0.1;

pub const CORRIDOR_SHALLOW_GAMMA_INITIAL_RAD: f64 = -0.001;
pub const CORRIDOR_STEEP_GAMMA_INITIAL_RAD: f64 = -0.4;
pub const CORRIDOR_SEARCH_STEPS: usize = 40;
pub const CORRIDOR_BISECTION_ITERATIONS: usize = 20;

pub const TARGET_APOAPSIS_BISECTION_ITERATIONS: usize = 30;
pub const TARGET_APOAPSIS_TOLERANCE_M: f64 = 1000.0;
pub const TARGET_GAMMA_TOLERANCE_RAD: f64 = 1e-6;
pub const DEFAULT_FALLBACK_ENTRY_ANGLE_RAD: f64 = -0.08;
pub const TARGET_CORRIDOR_APOAPSIS_MULTIPLIER: f64 = 1.5;

pub const ATMOSPHERIC_PASS_DEFAULT_MAX_DURATION_S: f64 = 3600.0;
pub const ATMOSPHERIC_PASS_DEFAULT_DT_S: f64 = 0.5;
pub const ATMOSPHERIC_PASS_FINE_DT_S: f64 = 0.2;
pub const ATMOSPHERIC_PASS_MIN_DT_S: f64 = 0.01;
pub const ATMOSPHERIC_PASS_MAX_DT_S: f64 = 5.0;
pub const ATMOSPHERIC_PASS_MIN_DURATION_S: f64 = 60.0;
pub const ATMOSPHERIC_PASS_HIGH_DENSITY_THRESHOLD: f64 = 1e-7;
pub const ATMOSPHERIC_PASS_EXO_DT_MULTIPLIER: f64 = 2.0;
pub const ATMOSPHERIC_ENTRY_ALTITUDE_BUFFER_M: f64 = 100.0;

pub const CHEBYSHEV_DEFAULT_FIT_DEGREE: usize = 7;

pub const CR3BP_COLLINEAR_CONVERGENCE_TOLERANCE: f64 = 1e-12;
pub const CR3BP_MAX_NEWTON_ITERATIONS: usize = 100;
pub const CR3BP_MIN_DISTANCE_SINGULARITY: f64 = 1e-8;
pub const CR3BP_MANIFOLD_EPSILON_DEFAULT: f64 = 1e-4;
pub const CR3BP_MANIFOLD_DEFAULT_STEP_COUNT: usize = 200;
pub const CR3BP_HALO_CORRECTION_MAX_ITERATIONS: usize = 50;
pub const CR3BP_HALO_CORRECTION_TOLERANCE: f64 = 1e-10;

pub const COWELL_DEFAULT_ABSOLUTE_TOLERANCE: f64 = 1e-10;
pub const COWELL_DEFAULT_RELATIVE_TOLERANCE: f64 = 1e-8;
pub const COWELL_MIN_TIME_STEP_S: f64 = 1e-3;
pub const COWELL_MAX_TIME_STEP_S: f64 = 86400.0;
pub const COWELL_DEFAULT_INITIAL_STEP_S: f64 = 60.0;
pub const COWELL_SAFETY_FACTOR: f64 = 0.9;
pub const COWELL_MIN_SCALE_FACTOR: f64 = 0.2;
pub const COWELL_MAX_SCALE_FACTOR: f64 = 5.0;

pub const N_BODY_PERTURBATION_RATIO_THRESHOLD: f64 = 0.02;
pub const HILL_SPHERE_MULTI_BODY_FRACTION: f64 = 0.65;
pub const LAGRANGE_ZONE_RADIUS_RATIO: f64 = 0.15;

pub const MAX_N_BODY_PROPAGATION_WINDOW_S: f64 = 864000.0;
pub const DEFAULT_BODY_ENCOUNTER_SEARCH_STEPS: usize = 100;
pub const MIN_ENCOUNTER_SEARCH_STEPS: usize = 10;
pub const ENCOUNTER_BISECTION_ITERATIONS: usize = 40;
pub const DEFAULT_AEROCAPTURE_VEHICLE_MASS_KG: f64 = 5000.0;
pub const DEFAULT_AEROCAPTURE_REFERENCE_AREA_M2: f64 = 10.0;
pub const DEFAULT_AEROCAPTURE_DRAG_COEFFICIENT: f64 = 0.5;
pub const DEFAULT_AEROCAPTURE_LIFT_TO_DRAG_RATIO: f64 = 0.0;
pub const DEFAULT_AEROCAPTURE_NOSE_RADIUS_M: f64 = 0.5;
pub const DEFAULT_AEROCAPTURE_MAX_HEAT_FLUX_W_PER_M2: f64 = 5.0e6;
pub const DEFAULT_AEROCAPTURE_MAX_G_LOAD: f64 = 10.0;
pub const DEFAULT_ATMOSPHERE_SURFACE_DENSITY_KG_PER_M3: f64 = 1.225;
pub const DEFAULT_ATMOSPHERE_SCALE_HEIGHT_M: f64 = 8500.0;
pub const DEFAULT_AEROCAPTURE_PASS_MAX_DURATION_S: f64 = 7200.0;
pub const DEFAULT_AEROCAPTURE_PASS_FALLBACK_DURATION_S: f64 = 600.0;
pub const ECCENTRICITY_PARABOLIC_TOLERANCE: f64 = 1e-6;
pub const ECCENTRICITY_CIRCULAR_TOLERANCE: f64 = 1e-8;

pub const DEFAULT_HULL_SOLAR_ABSORPTIVITY: f64 = 0.85;
pub const DEFAULT_SOLAR_RADIATION_PRESSURE_CR: f64 = 1.30;
pub const DEFAULT_SATELLITE_DRAG_COEFFICIENT_CD: f64 = 2.20;
pub const DEFAULT_PLANET_J3: f64 = -2.5327e-6;
pub const DEFAULT_PLANET_J4: f64 = -1.6196e-6;
pub const BESSEL_SERIES_TOLERANCE: f64 = 1e-12;
pub const BESSEL_MAX_TERMS: usize = 30;
pub const SECULAR_DECAY_MIN_PERIAPSIS_BUFFER_M: f64 = 1000.0;
pub const SECULAR_PROPAGATION_MAX_SUBSTEPS: usize = 1000;
pub const SECULAR_DECAY_MIN_ECCENTRICITY: f64 = 1e-7;
pub const SECULAR_DECAY_EPSILON: f64 = 1e-12;