[package]
name = "astronomicon-app"
version.workspace = true
edition.workspace = true

[dependencies]
astronomicon-core = { path = "../astronomicon-core" }
astronomicon-db = { path = "../astronomicon-db" }
sqlx.workspace = true
thiserror = "2.0"
tokio = { version = "1.0", features = ["rt-multi-thread"] }
uuid.workspace = true